package tugas_besar_pbo;

import java.awt.Color;
import javax.swing.JOptionPane;




public class homepage extends javax.swing.JFrame {

  Color DefaultColor,ClickedColor;
  
    public homepage() {
        initComponents(); 
        DefaultColor=new Color(255,255,255);
        ClickedColor=new Color(204,204,204);
        
        layanan_frame.setBackground(DefaultColor);
        Pesanan.setBackground(DefaultColor);
        Feedback.setBackground(DefaultColor);
        DPesanan.setBackground(DefaultColor);
        Pembayaran.setBackground(DefaultColor);
        
        Stats.setBackground(DefaultColor);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jpanel1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        LogoutButton = new javax.swing.JLabel();
        Stats = new javax.swing.JLabel();
        User = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        DPesanan = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        layanan_frame = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Pembayaran = new javax.swing.JPanel();
        pembayaran1 = new javax.swing.JLabel();
        Pesanan = new javax.swing.JPanel();
        pembayaran = new javax.swing.JLabel();
        Feedback = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard_Admin");
        setPreferredSize(new java.awt.Dimension(1100, 800));

        Jpanel1.setPreferredSize(new java.awt.Dimension(1100, 800));
        Jpanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(234, 234, 234));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoutButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\andhi\\OneDrive\\Dokumen\\images\\icons8-cross-48 (1).png")); // NOI18N
        LogoutButton.setText("jLabel2");
        LogoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutButtonMouseClicked(evt);
            }
        });
        jPanel1.add(LogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, 44, -1));

        Stats.setIcon(new javax.swing.ImageIcon("C:\\Users\\andhi\\OneDrive\\Dokumen\\images\\profile.png")); // NOI18N
        Stats.setText("Admin");
        Stats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StatsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                StatsMousePressed(evt);
            }
        });
        jPanel1.add(Stats, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        User.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        User.setText("user");
        jPanel1.add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 100, -1));

        jLabel2.setText("Logout");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 20, -1, -1));

        Jpanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, -1));

        jPanel2.setBackground(new java.awt.Color(31, 41, 130));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(180, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DPesanan.setBackground(new java.awt.Color(255, 255, 255));
        DPesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DPesananMousePressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\andhi\\OneDrive\\Dokumen\\images\\icons8-menu-24.png")); // NOI18N
        jLabel5.setText("Detail Pesanan");

        javax.swing.GroupLayout DPesananLayout = new javax.swing.GroupLayout(DPesanan);
        DPesanan.setLayout(DPesananLayout);
        DPesananLayout.setHorizontalGroup(
            DPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DPesananLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        DPesananLayout.setVerticalGroup(
            DPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        jPanel2.add(DPesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 170, -1));

        layanan_frame.setBackground(new java.awt.Color(255, 255, 255));
        layanan_frame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                layanan_frameMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                layanan_frameMousePressed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\andhi\\OneDrive\\Dokumen\\images\\icons8-menu-24.png")); // NOI18N
        jLabel8.setText("Layanan");

        javax.swing.GroupLayout layanan_frameLayout = new javax.swing.GroupLayout(layanan_frame);
        layanan_frame.setLayout(layanan_frameLayout);
        layanan_frameLayout.setHorizontalGroup(
            layanan_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layanan_frameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layanan_frameLayout.setVerticalGroup(
            layanan_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        jPanel2.add(layanan_frame, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 170, -1));

        jLabel1.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("©Barbershop Bogor");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 730, -1, -1));

        Pembayaran.setBackground(new java.awt.Color(255, 255, 255));
        Pembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PembayaranMousePressed(evt);
            }
        });

        pembayaran1.setIcon(new javax.swing.ImageIcon("C:\\Users\\andhi\\OneDrive\\Dokumen\\images\\icons8-menu-24.png")); // NOI18N
        pembayaran1.setText("Pembayaran");

        javax.swing.GroupLayout PembayaranLayout = new javax.swing.GroupLayout(Pembayaran);
        Pembayaran.setLayout(PembayaranLayout);
        PembayaranLayout.setHorizontalGroup(
            PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PembayaranLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pembayaran1)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        PembayaranLayout.setVerticalGroup(
            PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pembayaran1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        jPanel2.add(Pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 170, -1));

        Pesanan.setBackground(new java.awt.Color(255, 255, 255));
        Pesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PesananMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PesananMousePressed(evt);
            }
        });

        pembayaran.setIcon(new javax.swing.ImageIcon("C:\\Users\\andhi\\OneDrive\\Dokumen\\images\\icons8-menu-24.png")); // NOI18N
        pembayaran.setText("Pesanan");

        javax.swing.GroupLayout PesananLayout = new javax.swing.GroupLayout(Pesanan);
        Pesanan.setLayout(PesananLayout);
        PesananLayout.setHorizontalGroup(
            PesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PesananLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pembayaran)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        PesananLayout.setVerticalGroup(
            PesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pembayaran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        jPanel2.add(Pesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 170, -1));

        Feedback.setBackground(new java.awt.Color(255, 255, 255));
        Feedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FeedbackMousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\andhi\\OneDrive\\Dokumen\\images\\icons8-menu-24.png")); // NOI18N
        jLabel3.setText("Feedback");

        javax.swing.GroupLayout FeedbackLayout = new javax.swing.GroupLayout(Feedback);
        Feedback.setLayout(FeedbackLayout);
        FeedbackLayout.setHorizontalGroup(
            FeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FeedbackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        FeedbackLayout.setVerticalGroup(
            FeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        jPanel2.add(Feedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 170, -1));

        Jpanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 800));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(56, 13));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1100, 800));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1310, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );

        Jpanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 1310, 750));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jpanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jpanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtonMouseClicked
        int response = JOptionPane.showConfirmDialog(
        this, 
        "Apakah Anda Yakin Ingin Keluar?", 
        "Confirm Logout", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.QUESTION_MESSAGE
    );

    if (response == JOptionPane.YES_OPTION) {
        LoginPage loginPage = new LoginPage();
        loginPage.setVisible(true);
        loginPage.pack();
        loginPage.setLocationRelativeTo(null);
        this.dispose();
    }
    }//GEN-LAST:event_LogoutButtonMouseClicked

    private void layanan_frameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_layanan_frameMousePressed
        layanan_frame.setBackground(ClickedColor);
        Pesanan.setBackground(DefaultColor);
        Feedback.setBackground(DefaultColor);
        DPesanan.setBackground(DefaultColor); 
        Pembayaran.setBackground(DefaultColor);
    }//GEN-LAST:event_layanan_frameMousePressed

    private void PesananMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PesananMousePressed
        layanan_frame.setBackground(DefaultColor);
        Pesanan.setBackground(ClickedColor);
        Feedback.setBackground(DefaultColor);
        DPesanan.setBackground(DefaultColor);  
        Pembayaran.setBackground(DefaultColor);
    }//GEN-LAST:event_PesananMousePressed

    private void FeedbackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FeedbackMousePressed
        layanan_frame.setBackground(DefaultColor);
        Pesanan.setBackground(DefaultColor);
        Feedback.setBackground(ClickedColor);
        DPesanan.setBackground(DefaultColor);  
        Pembayaran.setBackground(DefaultColor);
    }//GEN-LAST:event_FeedbackMousePressed

    private void DPesananMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DPesananMousePressed
        layanan_frame.setBackground(DefaultColor);
        Pesanan.setBackground(DefaultColor);
        Feedback.setBackground(DefaultColor);
        DPesanan.setBackground(ClickedColor);    
        Pembayaran.setBackground(DefaultColor);
    }//GEN-LAST:event_DPesananMousePressed

    private void layanan_frameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_layanan_frameMouseClicked
        layananframe layanan_frame1=new layananframe ();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(layanan_frame1).setVisible(true);      
    }//GEN-LAST:event_layanan_frameMouseClicked

    private void StatsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StatsMouseClicked
        profileframe profile_frame1=new profileframe ();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(profile_frame1).setVisible(true);
        
    }//GEN-LAST:event_StatsMouseClicked

    private void StatsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StatsMousePressed
        Stats.setBackground(ClickedColor);
    }//GEN-LAST:event_StatsMousePressed

    private void PembayaranMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PembayaranMousePressed
        layanan_frame.setBackground(DefaultColor);
        Pesanan.setBackground(DefaultColor);
        Feedback.setBackground(DefaultColor);
        DPesanan.setBackground(DefaultColor);    
        Pembayaran.setBackground(ClickedColor);
    }//GEN-LAST:event_PembayaranMousePressed

    private void PesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PesananMouseClicked
        pesananframe pesanan_frame1=new pesananframe ();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(pesanan_frame1).setVisible(true);
    }//GEN-LAST:event_PesananMouseClicked
    public void setUser(String Name) {
        User.setText(Name);
    }
    
    public void setStats(String stats ) {
        Stats.setText(stats);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DPesanan;
    private javax.swing.JPanel Feedback;
    private javax.swing.JPanel Jpanel1;
    private javax.swing.JLabel LogoutButton;
    private javax.swing.JPanel Pembayaran;
    private javax.swing.JPanel Pesanan;
    private javax.swing.JLabel Stats;
    private javax.swing.JLabel User;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel layanan_frame;
    private javax.swing.JLabel pembayaran;
    private javax.swing.JLabel pembayaran1;
    // End of variables declaration//GEN-END:variables

}
