package tugas_besar_pbo;

import java.awt.Color;

public class homepage extends javax.swing.JFrame {

  Color DefaultColor,ClickedColor;
  
    public homepage() {
        initComponents(); 
        DefaultColor=new Color(255,255,255);
        ClickedColor=new Color(204,204,204);
        
        layanan_frame.setBackground(DefaultColor);
        Feedback.setBackground(DefaultColor);
        
        Stats.setBackground(DefaultColor);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jpanel1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Stats = new javax.swing.JLabel();
        User = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        layanan_frame = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Feedback = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard_Admin");
        setPreferredSize(new java.awt.Dimension(800, 600));

        Jpanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        Jpanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(234, 234, 234));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Stats.setIcon(new javax.swing.ImageIcon("C:\\Users\\andhi\\OneDrive\\Dokumen\\images\\profile.png")); // NOI18N
        Stats.setText("Admin");
        Stats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StatsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                StatsMousePressed(evt);
            }
        });
        jPanel1.add(Stats, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        User.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        User.setText("user");
        jPanel1.add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 100, -1));

        Jpanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, -1));

        jPanel2.setBackground(new java.awt.Color(31, 41, 130));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(180, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        layanan_frame.setBackground(new java.awt.Color(255, 255, 255));
        layanan_frame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                layanan_frameMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                layanan_frameMousePressed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\andhi\\OneDrive\\Dokumen\\images\\icons8-menu-24.png")); // NOI18N
        jLabel8.setText("Layanan");

        javax.swing.GroupLayout layanan_frameLayout = new javax.swing.GroupLayout(layanan_frame);
        layanan_frame.setLayout(layanan_frameLayout);
        layanan_frameLayout.setHorizontalGroup(
            layanan_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layanan_frameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layanan_frameLayout.setVerticalGroup(
            layanan_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        jPanel2.add(layanan_frame, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 170, -1));

        jLabel1.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("©Barbershop Bogor");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        Feedback.setBackground(new java.awt.Color(255, 255, 255));
        Feedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FeedbackMousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\andhi\\OneDrive\\Dokumen\\images\\icons8-menu-24.png")); // NOI18N
        jLabel3.setText("Feedback");

        javax.swing.GroupLayout FeedbackLayout = new javax.swing.GroupLayout(Feedback);
        Feedback.setLayout(FeedbackLayout);
        FeedbackLayout.setHorizontalGroup(
            FeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FeedbackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        FeedbackLayout.setVerticalGroup(
            FeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        jPanel2.add(Feedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 170, -1));

        Jpanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 190, 590));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(56, 13));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        Jpanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 930, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jpanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1120, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jpanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void layanan_frameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_layanan_frameMousePressed
        layanan_frame.setBackground(ClickedColor);
        Feedback.setBackground(DefaultColor);
    }//GEN-LAST:event_layanan_frameMousePressed

    private void FeedbackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FeedbackMousePressed
        layanan_frame.setBackground(DefaultColor);
        Feedback.setBackground(ClickedColor);
    }//GEN-LAST:event_FeedbackMousePressed

    private void layanan_frameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_layanan_frameMouseClicked
        layananframe layanan_frame1=new layananframe ();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(layanan_frame1).setVisible(true);      
    }//GEN-LAST:event_layanan_frameMouseClicked

    private void StatsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StatsMouseClicked
        profilFrame profile_frame1=new profilFrame ();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(profile_frame1).setVisible(true);
        
    }//GEN-LAST:event_StatsMouseClicked

    private void StatsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StatsMousePressed
        Stats.setBackground(ClickedColor);
    }//GEN-LAST:event_StatsMousePressed
    public void setUser(String Name) {
        User.setText(Name);
    }
    
    public void setStats(String stats ) {
        Stats.setText(stats);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Feedback;
    private javax.swing.JPanel Jpanel1;
    private javax.swing.JLabel Stats;
    private javax.swing.JLabel User;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel layanan_frame;
    // End of variables declaration//GEN-END:variables

}
